// CLI help text. Name lists come from the report / output registries
// so help stays in sync with wired-up entries.

import {emitNames} from "../common/emit-names.ts"
import {inspectorNames} from "../common/inspector-names.ts"
import {reportNames} from "../common/report-names.ts"

export function usage(): string {
    const reportFlags = reportNames.map((name) => `--${name}`).join(" ")
    const inspectorFlags = inspectorNames.map((name) => `--${name}`).join(" ")
    const emitFlags = emitNames.map((name) => `--emit ${name}`).join(" / ")

    return [
        "Usage: ts-refine <command> [options] [files...]",
        "",
        "Commands:",
        "  help                        Show this help (also: no args, -h, --help)",
        "  list                        List files with export / usage counts",
        "  inspect [--<inspector>...]  Per-file analysis (exports, importers, ...)",
        "  move <source...> <dest>     Move .ts files and rewrite import paths",
        "  rename --from <a> --to <b>  Rename an exported identifier project-wide",
        "  imports                     Organize imports (sort, merge, drop unused)",
        "  report [--<report>...]      Survey the codebase; print Markdown reports",
        "  format                      Apply inferred formatting conventions",
        "",
        "list (read; file export / usage listing):",
        "  list                        List every file with export / unused / importer counts",
        "                              (multiple list filters combine with AND)",
        "  --no-exports                Only files that export nothing",
        "  --no-importers              Only files no other file imports",
        "  --unused-exports            Only files with unused exports",
        "  --ref <target>              Only files that reference the target",
        "                              (an identifier, or a dotted a.b / a.b.c)",
        "",
        "inspect (read; per-file analysis):",
        "  inspect                     Run every inspector on every file",
        "  inspect --<inspector>...    Restrict to the named inspectors:",
        `                              ${inspectorFlags}`,
        "",
        "move (write; relocate .ts files and rewrite the import paths):",
        "  move <source...> <dest>     mv-style: dest may be a directory (multi-source)",
        "                              or a target filename (single-source rename).",
        "                              Paths are resolved against the tsconfig dir",
        "                              (same basis the other commands use).",
        "",
        "rename (write; rename an exported identifier and every reference):",
        "  rename --from <a> --to <b>  Rename the export `a` to `b` project-wide,",
        "                              updating importers and usages (aliases kept).",
        "  --from <a.b> --to <a.c>     A dotted name renames a member in place: a",
        "                              namespace member, or an interface/class property.",
        "  rename --from ... <file>    Scope a non-unique name to its defining file.",
        "",
        "imports (write; organize imports without reformatting the rest):",
        "  imports                     Sort, merge, and drop unused import/export",
        "                              declarations across every file (or the given",
        "                              files). Each file follows its own surveyed",
        "                              style, so the project's formatting barely shifts.",
        "  --check                     Report only; exit non-zero if any file would change",
        "",
        "report (read; the primary mode):",
        "  report                      Run every report and print the survey Markdown",
        "  report --<report>...        Restrict to the named reports:",
        `                              ${reportFlags}`,
        "  --emit <name>               Suppress Markdown and emit the named output instead",
        `                              ${emitFlags}`,
        `                              "ts-refine": ts-refine format's CLI arguments`,
        `                              "prettier": .prettierrc JSON`,
        `                              "stylistic": @stylistic/eslint-plugin rules JSON`,
        "",
        "format (write; follows inferred conventions):",
        "  format                      Apply the recommended formatting settings",
        "  --indent <N|tab>            Override indent width or use tabs",
        "  --semi <on|off>             Override semicolon insertion",
        "  --new-line <lf|crlf>        Override end-of-line",
        "  --bracket-spacing <on|off>  Override inner-brace spacing",
        "  --member-delimiter <v>      Override member delimiter (semi|comma|none)",
        "  --trailing-comma <on|off>   Override trailing commas in multi-line lists",
        "  --check                     Report only; exit non-zero if any file would change",
        "",
        "Global options (may appear before or after the command):",
        "  -p, --project <path>        Path to a tsconfig.json or a directory",
        "                              that contains one. Defaults to `-p .`.",
        "  --dry-run                   format/imports/move/rename only: print instead of writing",
        "  -h, --help                  Show this help",
        "",
        "See also: https://github.com/kawanet/ts-refine/blob/main/README.md",
    ].join("\n")
}
